# Generated by Django 5.0.6 on 2024-07-02 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singer', '0003_alter_singer_debut_alter_song_release'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singer',
            name='debut',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='song',
            name='release',
            field=models.TextField(),
        ),
    ]
